### ISSUE TITLE
点start后闪退问题

### ISSUE THREAD

**Issue by LCJDogLover** [Piasy/MediaCodecRcTest#1]
android monitor出现 这个storeMetaDataInBuffers (output) failed w/ err -2147483648问题
萌新 求教一下～

**Comment by Piasy** [comment]
这个日志不是闪退，实际上这个日志可以忽略：http://bigflake.com/mediacodec/#q12

**Comment by LCJDogLover** [comment]
FATAL EXCEPTION: EncoderThread  Process: com.github.piasy.mediacodecrctest, PID: 21244
android.media.MediaCodec$CodecException: Error 0x80001001

**Comment by Piasy** [comment]
嗯，这个才是崩溃的日志。你可以自己调试一番。
